<div {{ $attributes->class(['post-type', 'post-type_modal' => $isModal]) }}>
	<div class="post-type__item post-type__item_active">Все темы</div>
	<div class="post-type__item">Бега</div>
	<div class="post-type__item">Безопасность</div>
	<div class="post-type__item">Вестерн</div>
	<div class="post-type__item">Ветеринария</div>
	<div class="post-type__item">Видеосюжеты</div>
	<div class="post-type__item">Вольтижировка</div>
	<div class="post-type__item">Выбор и покупка лошади</div>
	<div class="post-type__item">Выездка</div>
	<div class="post-type__item">Выставки</div>
	<div class="post-type__item">За границей</div>
	<div class="post-type__item">Законодательство</div>
	<div class="post-type__item">История</div>
	<div class="post-type__item">Конкур</div>
	<div class="post-type__item">Кормление</div>
	<div class="post-type__item">Косметика для лошадей</div>
	<div class="post-type__item">Перевозка</div>
	<div class="post-type__item">Подбор амуниции</div>
	<div class="post-type__item">Путешествия</div>
	<div class="post-type__item">Сделай сам</div>
	<div class="post-type__item">Скачки</div>
	<div class="post-type__item">Смешное</div>
	<div class="post-type__item">Содержание</div>
	<div class="post-type__item">Соревнования</div>
	<div class="post-type__item">Строительство</div>
	<div class="post-type__item">Тренировки</div>
	<div class="post-type__item">Троеборье</div>
	<div class="post-type__item">Уход за копытами</div>
	<div class="post-type__item">Физподготовка всадника</div>
	<div class="post-type__item">Фотосессии</div>
</div>
